---
version: '3.3'

volumes:
  static_dir:
  media_dir:
  postgres_data:

services:
  db:
    image: postgres:15.2-alpine
    container_name: foodgram-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  backend:
    container_name: foodgram-backend
    # image: michaelburka/foodgram_backend:latest
    build: ../backend
    restart: always
    volumes:
      - static_dir:/app/static/
      - media_dir:/app/media/
    env_file:
      - ../.env

  frontend:
    container_name: foodgram-frontend
      # image: michaelburka/foodgram_frontend:latest
    build: ../frontend
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.23.3-alpine
    restart: always
    ports:
      # - 10000:80
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_dir:/etc/nginx/html/static/
      - media_dir:/etc/nginx/html/media/
    depends_on:
      - backend
      - frontend

...
